stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  IMAGE_REGISTRY: 65.108.52.119:5000
  IMAGE_NAME: web_app
  SWARM_MANAGER: 65.108.52.119

build-job:
  stage: build
  before_script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)

    - echo "${SSH_PRIVATE_KEY}" |  tr -d ' ' | base64 --decode
    - echo "${SSH_PRIVATE_KEY}" |  tr -d ' ' | base64 --decode | ssh-add -

    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    - ssh-keyscan $SWARM_MANAGER >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

    - ssh root@$SWARM_MANAGER "docker image ps"
  script:
    - echo $SWARM_MANAGER
    - ssh root@$SWARM_MANAGER "docker image ps"

    # -  ssh root@$SWARM_MANAGER "docker image rm $IMAGE_REGISTRY/$IMAGE_NAME"
    # - ssh root@SWARM_MANAGER

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
