stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  IMAGE_REGISTRY: 65.108.52.119:5000
  IMAGE_NAME: web_app
  SWARM_MANAGER: 65.108.52.119

build-job:
  stage: build
  before_script:
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - echo "Connected to remote server."
  script:
    - echo $SWARM_MANAGER
    - ssh root@$SWARM_MANAGER "docker image ps"

    # -  ssh root@$SWARM_MANAGER "docker image rm $IMAGE_REGISTRY/$IMAGE_NAME"
    # - ssh root@SWARM_MANAGER

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
