stages:
  - prepare
  - build
  - deploy

variables:
  IMAGE_REGISTRY: 65.108.52.119:5000
  IMAGE_NAME: web_app
  SWARM_MANAGER: 65.108.52.119
  ORIGIN_NAME: gitlab

.prepare-job-get-secret:
  stage: prepare
  image: python:3.9
  rules:
    - if: '$CI_COMMIT_BRANCH == "TEST" || $CI_COMMIT_BRANCH == "PROD"'
  services:
    - name: waryak/karpov_courses:secret_ci_service
      alias: waryak
  script:
    - export SOURCE_BRANCH_LOW=$(echo $CI_COMMIT_BRANCH | tr '[:upper:]' '[:lower:]')
    - echo http://waryak:5000/get_secret_number/${SOURCE_BRANCH_LOW}
    - SECRET_NUMBER=$(curl -s http://waryak:5000/get_secret_number/${SOURCE_BRANCH_LOW})
    - echo $SECRET_NUMBER
    - echo $SECRET_NUMBER > ./secret.txt
  artifacts:
      paths:
        - ./secret.txt


build-job:
  stage: build
  before_script:
    # - export SECRET_NUMBER=$(cat ./secret.txt | grep -oP '(?<="secret_number":)\d+')
    - echo $SECRET_NUMBER
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "${SSH_PRIVATE_KEY_ENCODED}" | base64 --decode | ssh-add -
    - ssh root@$SWARM_MANAGER "ls"
    - echo "Successfuly connected to remote server."
  script:
    - ssh root@$SWARM_MANAGER "cd $CI_PROJECT_NAME"
    - ssh root@$SWARM_MANAGER "pwd"
    - ssh root@$SWARM_MANAGER "git pull $ORIGIN_NAME $CI_COMMIT_BRANCH"
    - ssh root@$SWARM_MANAGER "git checkout $CI_COMMIT_BRANCH"
    - ssh root@$SWARM_MANAGER "git pull origin $CI_COMMIT_BRANCH"
    # - ssh root@$SWARM_MANAGER 
    # - ssh root@$SWARM_MANAGER "docker image rm $IMAGE_REGISTRY/$IMAGE_NAME"
    # - ssh root@$SWARM_MANAGER "docker pull $IMAGE_REGISTRY/$IMAGE_NAME"
  



.deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
